### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by amrmugl** [a5hk/night-coder#21]
I've been using this theme for more than a year or maybe 2. The night coder gray theme, that was my default one since it came out but it's been removed. 

Any reason you removed it? If you can bring it back that would be awesome otherwise no worries. I've been using warm theme since then. 

Thank you for creating such beautiful themes :)

**Comment by a5hk** [comment]
Sorry for the inconvenience. I will bring it back. 

I thought by removig it I will have more time to support the remaining ones. But in the end that didn't make any difference. And I have/had plans to add a few more. I tried to reduce the number of themes to reduce the clutter in the theme selection menu. Since I have no usage data I and no way to announce new releases, I assumed no one knows about the variant and thus no one uses that variant. I was wrong apparently.

It will be back in a day or two.

**Comment by amrmugl** [comment]
Thanks i really appreciate your work...
